title: Dino Tutors
email: info@dinotutors.com
description: Dino Tutors is an example of a company in the tutoring industry, showcasing the power of intergrating TutorCruncher into your website.
baseurl: ''
url: 'http://dinotutors.com'
meta_author: Tom Hamilton Stubber

# Build settings
markdown: kramdown
theme: minima
permalink: pretty
highlighter: pygments

socket_key: 390eb8d224a0f64395eb
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
include:
  - _redirects
collections:
  examples:
    title: Examples
    output: true
footer:
  copyright: TutorCruncher
address:
  - The Food Exchange
  - SW8 5EL, London
social:
  - title: twitter
    url: http://twitter.com/tutorcruncher
  - title: facebook
    url: http://facebook.com/tutorcruncher
  - title: github
    url: http://github.com/tutorcruncher

socket_url: https://cdn.tutorcruncher.com/socket/latest/socket.js
